### ISSUE TITLE
humbug it's not installable in a Symfony 3.x project

### ISSUE THREAD

**Issue by agiuliano** [humbug/humbug#171]
Since even the dev-master version require `symfony/process: 2.6`, Humbug is not installable in a project using Symfony 3.0.

**Comment by Anahkiasen** [comment]
👍  for this

**Comment by aztech-dev** [comment]
There's an open P/R for this, #181 which is pending merge

**Comment by theofidry** [comment]
Humbug should not installed as a dev dependency in the first place, you should use the phar or tools like https://github.com/bamarni/composer-bin-plugin to handle your project dependencies.

**Comment by theofidry** [comment]
@padraic this issue can be closed as #181 has been merged :)
