### ISSUE TITLE
Don't require xdebug for code coverage

### ISSUE THREAD

**Issue by nesl247** [humbug/humbug#178]
At the moment Xdebug has an issue with opcache when enabled on cli in PHP 7. Because of this I can't actually use xdebug for code coverage which led me to read about phpdbg. Because phpunit works just fine with that, I really think humbug should support it as well.

To run code coverage I simply run `phpdbg -qrr bin/phpunit --coverag-clover=coverage.xml` and it works just fine.

**Comment by svemir** [comment]
I have added phpdbg support elsewhere before and may be able to look into adding it here as well, but for me at least humbug works fine with xdebug and php 7.0.5 (and in an interesting twist, there are some issues with phpdbg and php 7.0.7...)

**Comment by padraic** [comment]
Note: Include support for this in documentation before closing this issue. Seems to be well worth a mention.

**Comment by theofidry** [comment]
See #200

**Comment by theofidry** [comment]
Closed as #200 has been merged
