### ISSUE TITLE
Support for PHPSpec

### ISSUE THREAD

**Issue by filipgolonka** [humbug/humbug#192]
@padraic and community - great work on this library! Thanks!

I would really appreciate to have a support also for PHPSpec - some of projects aren't using PHPUnit. Your tool allow developer to measure quality of his tests, so it would be nice to allow measuring also quality of specs :)

**Comment by wsromek** [comment]
👍

**Comment by arkadiuszmalina** [comment]
👍

**Comment by theofidry** [comment]
See #145

**Comment by padraic** [comment]
Reminder to self that there is a phpspec branch... The plan, before I vanished, was to improve the code quality, and then add phpspec support. There's at least some basic set of adapter work hanging around in a branch when that day comes.

**Comment by padraic** [comment]
Closing in favour of addition of 2.0 roadmap where we'll track going forward.
