### ISSUE TITLE
No maintainance anymore?

### ISSUE THREAD

**Issue by alexz707** [humbug/humbug#209]
It seems that this repository isn't maintained any more?
The last commit was in Aug 2016 and the PR aren't accepted or declined.
phpunit 6.0 support would be also needed ;)

@padraic Could you please tell us your further plans regarding this great project ?

thanks ;)

**Comment by tommy-muehle** [comment]
See https://twitter.com/padraicb/status/844455293727789056

**Comment by alexz707** [comment]
Thanks for the info! 👍

**Comment by padraic** [comment]
See #212

**Comment by alexz707** [comment]
Thanks, have already seen it yesterday ;)
I appreciate your "comeback"!
