### ISSUE TITLE
Deprecation notices stop Humbug

### ISSUE THREAD

**Issue by pvdleek** [humbug/humbug#211]
[exec] Tests must be in a fully passing state before Humbug is run.
     [exec] Incomplete, skipped or risky tests are allowed.
     [exec] The testing framework reported an exit code of 1.
     [exec] Stdout:
     [exec]    > TAP version 13
     [exec]    > 
     [exec]    > Generating code coverage report in PHP format ... done
     [exec]    > 
     [exec]    > Remaining deprecation notices (1)
     [exec]    > 
     [exec]    > Using a colon that is not followed by an indication character (i.e. " ", ",", "[", "]", "{", "}" is deprecated since version 3.2 and will throw a ParseException in 4.0: 1x
     [exec]    >     1x in xxxTest::setUp from AppBundle\Tests\Entity
     [exec]    > 
     [exec]    > 
     [exec]  2160 [-------------->-------------------------------------------] 2 mins
     [exec] Result: 1

**Comment by stof** [comment]
The Symfony PHPUnit Bridge will by default make test fail when finding a deprecation in a non-legacy test.

@humbug/core I suggest setting the bridge in weak mode when running humbug (or even in disabled mode), thanks to the dedicated env variable.

**Comment by stof** [comment]
@padraic looks like only collaborators can mention the core team currently. It would be useful to make the team public instead

**Comment by theofidry** [comment]
@stof from what I see the team _is_ public, and all its members as well.

**Comment by padraic** [comment]
Hmm, seems the mentions only kick in for org members, not non-members. I just checked the docs, and that seems to be the expected behaviour. Unfortunate, but I assume in a larger org it may be a problem to have large teams subscribed to issues by non-members unnecessarily.

**Comment by stof** [comment]
hmm indeed, non org members can never mention teams. I thought they were able to mention public teams.
Too bad for open-source projects were most people involved are not member of the org

**Comment by padraic** [comment]
I'm assuming we can just screen the PHPUnit listeners for the bridge, and then add the env change, or is there any other means of injecting these notices to be aware of?

**Comment by stof** [comment]
Well, you could just always set the `SYMFONY_DEPRECATION_HELPER=weak` env variable when running PHPUnit. It won't hurt if the bridge is not used
