### ISSUE TITLE
Set up Travis & Scrutinizer for humbug organisation

### ISSUE THREAD

**Issue by pamil** [humbug/humbug#216]
Admin permissions needed, badges included in readme should be updated as well.

**Comment by padraic** [comment]
@pamil I've approved the access requests.

**Comment by pamil** [comment]
@padraic Travis looks fine, Scrutinizer needs to be set up at https://scrutinizer-ci.com/g/new

**Comment by GrahamCampbell** [comment]
StyleCI is also needed too.

**Comment by padraic** [comment]
@pamil @GrahamCampbell I've ran through both services and added/approved. StyleCI auto-PR is here: https://github.com/humbug/humbug/pull/218

**Comment by padraic** [comment]
Leaving this open if there are any other related items to note.

**Comment by padraic** [comment]
Should probably note that I've done this for ALL repos currently in the organisation!

**Comment by padraic** [comment]
StyleCI now in passing state. Low handing fruit and all, but :grin:

**Comment by theofidry** [comment]
From what I see this has been done for all repos so should be ok :)
