### ISSUE TITLE
Make Humbug tests up and running

### ISSUE THREAD

**Issue by pamil** [humbug/humbug#219]
From the lowest versions:
 - PHP 5.5 build fails because of changed `Symfony\Component\Console\Application::getLongVersion()` from `symfony/console` somewhere in between `2.8.19` and `3.2.7`, it should be solved by overriding its definition
 - PHP 5.6 build fails because of calling unexisting `PHPUnit_Util_Configuration::getTestdoxGroupConfiguration()` from `phpunit/phpunit` somewhere in between `4.8.35` and `5.7.19`, needs to be investigated

No more changes needed to get Travis green, removing `hhvm-nightly` and matrix configuration is already done in #207.

**Comment by pamil** [comment]
The strange failures for PHP 5.6 and PHP 7.0 are caused by Humbug using a PHPUnit binary provided with `phpenv`, so PHP 7.0 uses PHPUnit 6.0 even when Composer installs PHPUnit 5.7 to `vendor/bin`.

**Comment by padraic** [comment]
Merged both PRs for you. Should be close to having all our 3rd party service support back in order after today!

**Comment by pamil** [comment]
After having a deeper look, Composer does not return correct binaries directory because Behat changes current working directory to something like `/tmp/humbug-behat6b5eee` and there's no `composer.json`. This causes Humbug to look for `phpunit` using `$PATH` environmental variable.
