### ISSUE TITLE
Communication channels

### ISSUE THREAD

**Issue by theofidry** [humbug/humbug#223]
To @humbug/core 

Also I already mentioned that to @padraic but I think I should re-iterate with the whole team: I think it would be good to have a Slack channel (I was suggestion #testing, #mutation-testing or create a #humbug of [symfony-dev](https://symfony-devs.slack.com/shared_invite/MTYxMjcxMjc0MTc5LTE0OTA3ODE4OTQtYzc4NWVmMzRmZQ)) or a dedicated Slack team for some discussions and/or support. 

I'm suggesting symfony-dev as mainly because 1. I'm already there, 2. the community is quite active and 3. I already did it for nelmio/alice and it's working well (and I kinda prefer hijack an existing team rather than creating yet another slack team :P)

Whatever channel of communication we pick we could also add a badge in the readme, e.g.:

```
[![Slack](https://img.shields.io/badge/slack-%23humbug-blue.svg?style=flat-square)](https://slackinvite.me/to/symfony-devs)
```
[![Slack](https://img.shields.io/badge/slack-%23humbug-blue.svg?style=flat-square)](https://slackinvite.me/to/symfony-devs)

**Comment by pamil** [comment]
:+1:, #humbug @ symfony-dev slack is the most simple yet sufficent option :)

**Comment by padraic** [comment]
My time online in chat will be reasonably small, but that's the point of you three being here :grin: I say fire away if @MarkRedeman has no objections.

**Comment by MarkRedeman** [comment]
I just joined the symfony-dev slack. :)

There is also a [mutation-testing](https://mutation-testing-slack.herokuapp.com/) slack which has various channels of other mutation testing projects.

**Comment by mbj** [comment]
I happily invite the administrators of this repository to the mutation testing slack channel and will give them admin rights.

**Comment by theofidry** [comment]
Joined both 😄 

Alright I think we're somewhat done with that thread then. @padraic if you can join us there that would be great, even if we won't chat in real time very often :)

**Comment by padraic** [comment]
All signed up ;)

**Comment by mbj** [comment]
If you ever want move over to the mutation testing slack let me know.

**Comment by theofidry** [comment]
Thanks @mbj, we'll be there as well for more mutation testing oriented things (as opposed to Symfony-dev which is more PHP oriented) :)
