### ISSUE TITLE
Path to PHPUnit not properly escaped

### ISSUE THREAD

**Issue by mikemand** [humbug/humbug#225]
Hello,

The path to PHPUnit is not escaped (or quoted) at all. I get the following:

<details>
Tests must be in a fully passing state before Humbug is run.<br>
Incomplete, skipped or risky tests are allowed.<br>
The testing framework reported an exit code of 2.<br>
The testing framework ran into a failure or error. Refer to output below.<br>
Stderr:<br>
   > sh: -c: line 0: syntax error near unexpected token `('<br>
   > sh: -c: line 0: `exec /usr/local/Cellar/php70/7.0.17_9/bin/php /path/to/project/vendor/phpunit/phpunit/phpunit --configuration=/var/folders/7k/stspwzjd4d5192r3llqsqzfw0000gp/T/humbug/phpunit.humbug.xml --stop-on-failure --tap '<br>
   >
</details>

**Comment by mikemand** [comment]
This might be a duplicate of #199. I saw that issue right after posting mine.

**Comment by theofidry** [comment]
Let's close this if it's a duplicate then :)
