### ISSUE TITLE
You need to install and enable xdebug in order to.. even with xdebug installed

### ISSUE THREAD

**Issue by vasilvestre** [humbug/humbug#268]
| Question    | Answer
| ------------| ---------------
| Humbug ver. | 1-0@dev
| Adapter ver.| PHPUnit 4.8
| Platform    | Windows
| PHP ver.    | Php 5.4

I've installed Humbug with "composer global require "humbug/humbug". Install worked but when I launch "humbug configure" in order to .. well, configure .. it show me "You need to install and enable xdebug in order to allow for code coverage generation."

phpinfo() show me that xdebug is installed. I don't get why it won't work

**Comment by jyggen** [comment]
Did you check `phpinfo()` through the web server or CLI? They tend to use different .ini files and thus can have different extensions enabled.

**Comment by vasilvestre** [comment]
@jyggen good job. I've just learned something.. I still don't understand how my CLI is using another version of php but .. I will try
Thanks !

**Comment by vasilvestre** [comment]
@jyggen good job. I've just learned something.. I still don't understand how my CLI is using another version of php but .. I will try
Thanks !
