### ISSUE TITLE
Humbug stops, saying tests must pass, but they do

### ISSUE THREAD

**Issue by Anahkiasen** [humbug/humbug#39]
I'm getting a weird bug in the latest version, Humbug just stops and tell me my test must pass for it to run properly, but when I run the tests they all pass properly:

```
$ humbug
Humbug running test suite to generate logs and code coverage data...

   21 [==========================================================] 33 secs

<warning>Tests must be in a fully passing state before Humbug is run.</warning>
<warning>Incomplete, skipped or risky tests are allowed.</warning>
<warning>The testing framework reported an exit code of 143.</warning>
<warning>The testing framework ran into a failure or error. Refer to out below.</warning>
<warning>Stdout: \n    > ok 22 - Rocketeer\Abstracts\AbstractTaskTest::testCanGetOptionsViaCommandOrSetters
    > not ok 23 - Error: Rocketeer\Abstracts\Strategies\AbstractDependenciesStrategyTest::testCanShareDependenciesFolder
    > \n</warning>
```

```
$ phpunit
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /Users/anahkiasen/Sites/rocketeers/rocketeer/phpunit.xml

...............................................................  63 / 323 ( 19%)
............................................................... 126 / 323 ( 39%)
............................................................... 189 / 323 ( 58%)
............................................................... 252 / 323 ( 78%)
............................................................... 315 / 323 ( 97%)
........

Time: 38.27 seconds, Memory: 389.75Mb

OK (323 tests, 400 assertions)
```

The progress bar is complete so I assumed this was just a warning but the humbug log is empty and just contains the error above

**Comment by padraic** [comment]
Can you try running phpunit with the --tap option and see what it spits out at that point?

**Comment by Anahkiasen** [comment]
Nothing in particular, full test suite says `ok`.

**Comment by Anahkiasen** [comment]
Are the mutations tested in parallel? Cause my tests involve the filesystem being modified, if two tests were to run in parallel it is possible that one test would cause another test's failure

**Comment by padraic** [comment]
The tests would be generating a junit log, and also code coverage is running (php format). No test reordering is done for the initial run since we're only out to gather data at that point.

**Comment by Anahkiasen** [comment]
Repository I'm testing this on is [public](https://github.com/rocketeers/rocketeer) if that can help you debug yourself

**Comment by padraic** [comment]
Here's what I get running phpunit (without Humbug):
```
PHPUnit 4.4.2 by Sebastian Bergmann.

Configuration read from /home/padraic/projects/play/rocketeer/phpunit.xml

...............................................................  63 / 268 ( 23%)
............................................................... 126 / 268 ( 47%)
..F.FF......................................................... 189 / 268 ( 70%)
.......sh: 1: bundle: not found
sh: 1: composer: not found
..................PHP Fatal error:  Call to a member function format() on boolean in /home/padraic/projects/play/rocketeer/src/Rocketeer/Abstracts/AbstractTask.php on line 251
PHP Stack trace:
PHP   1. {main}() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/TextUI/Command.php:103
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/TextUI/Command.php:151
PHP   5. PHPUnit_Framework_TestSuite->run() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:388
PHP   6. PHPUnit_Framework_TestSuite->run() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
PHP   7. PHPUnit_Framework_TestCase->run() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
PHP   8. PHPUnit_Framework_TestResult->run() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestCase.php:687
PHP   9. PHPUnit_Framework_TestCase->runBare() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestResult.php:609
PHP  10. PHPUnit_Framework_TestCase->runTest() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestCase.php:731
PHP  11. ReflectionMethod->invokeArgs() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestCase.php:846
PHP  12. Rocketeer\Tasks\CurrentReleaseTest->testCanGetCurrentRelease() /home/padraic/projects/play/rocketeer/vendor/phpunit/phpunit/src/Framework/TestCase.php:846
PHP  13. Rocketeer\TestCases\RocketeerTestCase->assertTaskOutput() /home/padraic/projects/play/rocketeer/tests/Tasks/CurrentReleaseTest.php:17
PHP  14. Rocketeer\Tasks\CurrentRelease->execute() /home/padraic/projects/play/rocketeer/tests/TestCases/Modules/RocketeerAssertions.php:66
PHP  15. Rocketeer\Abstracts\AbstractTask->displayReleases() /home/padraic/projects/play/rocketeer/src/Rocketeer/Tasks/CurrentRelease.php:63
```

**Comment by Anahkiasen** [comment]
Well that's rather peculiar, all the tests pass [on Travis](https://travis-ci.org/rocketeers/rocketeer/builds/47257376) with all PHP versions and both highest and lowest set of dependencies

**Comment by padraic** [comment]
Will be looking through those in case I missed any setup here.

**Comment by redbeardcreator** [comment]
If case it helps, I've got a similar situation. Running against redbeardcreator/parse@e7d0f65d1f9dfcdd7ed6d4b6dffc769ef07db3f8 with the `humbug.json` file

```json
{
    "timeout": 10,
    "source": {
        "directories": [
            "src"
        ]
    },
    "logs": {
        "text": "humbuglog.txt",
        "json": "humbuglog.json"
    }
}
```

I get the error warning:

> &lt;warning>Tests must be in a fully passing state before Humbug is run.&lt;/warning>
> &lt;warning>Incomplete, skipped or risky tests are allowed.&lt;/warning>
> &lt;warning>The testing framework reported an exit code of 143.&lt;/warning>
> &lt;warning>The testing framework ran into a failure or error. Refer to out below.&lt;/warning>
> &lt;warning>Stdout: \n    > ok 118 - Psecio\Parse\Subscriber\SubscriberTest::testEmptyMethods
> &nbsp;&nbsp;&nbsp;&nbsp;> not ok 119 - Error: Psecio\Parse\Subscriber\XmlTest::testGenerateXml
> &nbsp;&nbsp;&nbsp;&nbsp;> \n&lt;/warning>

With `--tap`:

> ...
> ok 117 - Psecio\Parse\Subscriber\SubscriberTest::testSubscription
> ok 118 - Psecio\Parse\Subscriber\SubscriberTest::testEmptyMethods
> ok 119 - Psecio\Parse\Subscriber\XmlTest::testGenerateXml
> 1..119

The weird thing is, if I go back a commit to redbeardcreator/parse@c459d99271f05a034b3cfd1902f2d2509d1a5be2 everything's fine.

I have verified that I've pulled the latest commit of humbug, with the latest version of composer and the latest versions of the dependencies for both humbug and parse.

**Comment by padraic** [comment]
Thanks @redbeardcreator. Will check it out later.

**Comment by Anahkiasen** [comment]
On my end it works now. Well I think. I got 0 escapes so I'm not sure which is more suspicious :d

**Comment by Anahkiasen** [comment]
Seems to be happening again:

```
Macedoine ➜  rocketeer git:(develop) phpunit
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /Users/anahkiasen/Sites/rocketeers/rocketeer/phpunit.xml

...............................................................  63 / 386 ( 16%)
............................................................... 126 / 386 ( 32%)
............................................................... 189 / 386 ( 48%)
............................................................... 252 / 386 ( 65%)
............................................................... 315 / 386 ( 81%)
............................................................... 378 / 386 ( 97%)
........


Time: 48.55 seconds, Memory: 493.25Mb

OK (386 tests, 480 assertions)
Macedoine ➜  rocketeer git:(develop) humbug -vvv

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------] 3 secs

 Tests must be in a fully passing state before Humbug is run.
 Incomplete, skipped or risky tests are allowed.
 The testing framework reported an exit code of 143.
 The testing framework ran into a failure or error. Refer to output below.
 Stdout:
    > TAP version 13
    > not ok 1 - Error: Rocketeer\Abstracts\AbstractBinaryTest::testCanExecuteMethod
    >
```

**Comment by Anahkiasen** [comment]
Any news on this one? Using the PHAR currently so it can't be a global autoload issue or anything, and there is literally no output to try to see what the error seems to be

**Comment by padraic** [comment]
There's a significant change upcoming in how PHPUnit is integrated, so I'm waiting on that to see if it resolves a few compatibility issues. Essentially we're trading off using the internal PHPUnit for compatibility and just checking what is actually used locally and using that instead. It will break things differently for unit tests using old versions of PHPUnit, but should help with anyone having issues on newer versions of PHPUnit.

Will revisit this and some of the other issues once that's in place.

**Comment by domnikl** [comment]
Anything new on this one? It's been some time since 27 Mar.

**Comment by padraic** [comment]
I've wrapped up some PHPUnit integration changes recently, so I'm not sure if it's still an issue. Will need to be rechecked once I roll a new phar build (currently doing work on phar-update before that). As I recall, one issue I had before (hopefully fixed) was that the Rocketeer tests had some hard dependencies on the repo's base directory contents so I couldn't get the then tests in master to pass locally even without Humbug.

I'll mark this issue (other related ones already are) as a bug. Will be going over all of these to fix what I can prior to the 1.0.0 stable release.

**Comment by domnikl** [comment]
I checked again and it works for me with the current dev version!

**Comment by offdev** [comment]
Hi,

I am having the same issue, tests passing (tested on several PHPUnit 5.x versions), but humbug says it doesn't.

`$ phpunit
PHPUnit 5.5.0 by Sebastian Bergmann and contributors.

...........................                                       27 / 27 (100%)

Time: 423 ms, Memory: 12.00MB

OK (27 tests, 61 assertions)`

`$ humbug

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    4 [==========================================================]  1 sec

Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 143.
The testing framework ran into a failure or error. Refer to output below.
Stdout:
   > TAP version 13
   > ok 1 - Some\Company\Channel\IteratorTest::testIterator
   > ok 2 - Some\Company\Channel\IteratorTest::testIteratorWithEmptyItems
   > ok 3 - Some\Company\Channel\IteratorTest::testAppendIterator
   > ok 4 - Some\Company\Channel\IteratorTest::testEmptyAppendIterator
   > not ok 5 - Error: Some\Company\Channel\Member\FactoryTest::testGetChannel_shouldReturnMemcacheDao
   >`

**Comment by alessiopiazza** [comment]
I'm having the same issue 
test suite green but humbug says that it's not

phpunit --tap
`ok 124 - Drupal\Tests\ect_event\Unit\EventExportDataToCsvTest::testFormat`

humbug
`not ok 124 - Error: Drupal\Tests\ect_event\Unit\EventExportDataToCsvTest::testFormat`

PHP 7.0.8
PHPUnit 4.8.26

I tried to exclude this single test but Humbug mark as failure the very next one of the same class. My only option to procede  is to exclude them all.
I'm running humbug on a suit with more than 1000 assertions and this happens a lot...

**Comment by zf2timo** [comment]
I'm also having this issue.

System Environment:
Ubuntu 16.04
PHP 7.0.8
PHPUnit 5.3.4

```
$  php humbug.phar -vvv
 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec

Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 143.
The testing framework ran into a failure or error. Refer to output below.
Stdout:
   > TAP version 13
   > not ok 1 - Error: RabbitMQTest\Channel\Wrapper\ChannelTest::testWrapperExecutesWaitMethod
   > 
```

```bash
$ ./vendor/bin/phpunit --tap 
TAP version 13
ok 1 - RabbitMQTest\Channel\Wrapper\ChannelTest::testWrapperExecutesWaitMethod
....
ok 29 - RabbitMQTest\Receiver\WorkerReceiverTest::testChannelException
1..29

Generating code coverage report in HTML format ... done

Generating code coverage report in PHPUnit XML format ... done
```

**Comment by sblaut** [comment]
Having the same problem. 

PHP: 7.0
phpunit: 5.4.8

> $ ./vendor/bin/phpunit -c app --tap
TAP version 13
Clock-mocked namespaces for SymfonyTestsListener need to be nested in a "time-sensitive" key. This will be enforced in Symfony 4.0.
Testing Project Test Suite
ok 1 - Api\JsonApi\Deserializer\GroupDeserializerTest::testDeserialize_TimeIsNull
[...]


Humbug:

> $~/.composer/vendor/bin/humbug -vvv
>
> _  _            _
>| || |_  _ _ __ | |__ _  _ __ _
>| __ | || | '  \| '_ \ || / _` |
>|_||_|\_,_|_|_|_|_.__/\_,_\__, |
>                          |___/ 
>Humbug version 1.0-dev
>
>Humbug running test suite to generate logs and code coverage data...
>
>   0 [>---------------------------------------------------------]  1 sec
>
>Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 143.
The testing framework ran into a failure or error. Refer to output below.
Stdout:
   > TAP version 13
   > not ok 1 - Error: Api\JsonApi\Deserializer\GroupDeserializerTest::testDeserialize_TimeIsNull
   >

**Comment by MaxenceDupressoir** [comment]
Same issue here: 
```bash
bin/phpunit --tap --bootstrap /var/www/meetic/api-exposure-layer/app/bootstrap.php.cache --configuration /var/www/meetic/api-exposure-layer/humbug/phpunit.xml /var/www/meetic/api-exposure-layer/tests
TAP version 13
ok 1 - Ilius\Account\Application\ContactInformationHandlerTest::testGetContactInformationShouldReturnValidAccountWithContactInformation
[...]
```

Humbug using phar :
```bash
php humbug.phar -vvv

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec

Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 143.
The testing framework ran into a failure or error. Refer to output below.
Stdout:
   > TAP version 13
   > not ok 1 - Error: Ilius\ApiClient\SocialEvents\Uge\Tests\Services\UgeApiTest::testGetList
   > 
```

**Comment by theofidry** [comment]
To those who are using a PHAR, can you try *without* a PHAR? If it solves the issue, it is likely that your code is using a library in common with Humbug. The library used will be the one from the PHAR, which might not be the one your application is using, resulting in random failures like that.

If you're interested in solving that kind of issue, I recommend you to take a look at https://github.com/webmozart/php-scoper which needs help.

**Comment by msvrtan** [comment]
I'we got this error too, after half an hour of trying to figure it out, issue was `covers` annotation, it was pointing to non existing class (my typo).

Maybe this helps someone

**Comment by theofidry** [comment]
Indeed it's worth noting humbug runs phpunit with coverage, and unless you run phpunit with coverage, you don't have any failure with a wrong `@covers` annotation.

**Comment by zf2timo** [comment]
> To those who are using a PHAR, can you try without a PHAR? If it solves the issue, it is likely that your code is using a library in common with Humbug.
Thank you @theofidry for the Tip. After i installed Humbug globally via composer i can execute it.

**Comment by ptsilva** [comment]
@theofidry, i tried run without phar. And it's works

**Comment by theofidry** [comment]
So it's likely to be a weird issue regarding a difference of version between a package used both in the PHAR and your code. As you may already know, the code bundled in the PHAR is not isolated, so if a class `Foo` is autoloaded in the PHAR and you have a class `Foo` in your code, the one from the PHAR will be used.

That's the kind of issue we are trying to tackle with https://github.com/humbug/php-scoper. We plan to use it for future versions, meanwhile going without a PHAR when that issue occurs is probably a good idea

**Comment by ccwebdesign** [comment]
Adding to this, running from master/bin, humbug failed until I pulled 'stderr="true"' from phpunit.xml. Other settings that didn't cause an issue for me:
bootstrap
colors
verbose
filter (whitelist)
logging

**Comment by theofidry** [comment]
@ccwebdesign that looks like a different issue to me. Do you mind opening another one with maybe more details about the error you are getting with what configuration?

**Comment by theofidry** [comment]
Meanwhile I'm closing this issue, as I explained above there is not much we can do before PHP-Scoper is out except mitigating it by installing it as a dependency instead of a PHAR.

**Comment by ccwebdesign** [comment]
@theofidry Sure -- submitted.
