### ISSUE TITLE
Getting insta-failure on running

### ISSUE THREAD

**Issue by Anahkiasen** [humbug/humbug#69]
```
Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec

 Tests must be in a fully passing state before Humbug is run.
 Incomplete, skipped or risky tests are allowed.
 The testing framework reported an exit code of 255.
 Stdout:
    >
    > Fatal error: Cannot redeclare class PhpParser\Autoloader in /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/nikic/php-parser/lib/PhpParser/Autoloader.php on line 9
    >
    > Call Stack:
    >     0.0002     225536   1. {main}() -:0
    >     0.0050     807768   2. Humbug\Adapter\Phpunit::main() -:6
    >     0.0068     979536   3. PHPUnit_TextUI_Command->run() /Users/anahkiasen/.composer/vendor/humbug/humbug/src/Humbug/Adapter/Phpunit.php:157
    >     0.0068     982256   4. PHPUnit_TextUI_Command->handleArguments() /Users/anahkiasen/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:114
    >     0.0131    1577768   5. PHPUnit_TextUI_Command->handleBootstrap() /Users/anahkiasen/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:622
    >     0.0132    1588200   6. PHPUnit_Util_Fileloader::checkAndLoad() /Users/anahkiasen/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:792
    >     0.0133    1588624   7. PHPUnit_Util_Fileloader::load() /Users/anahkiasen/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
    >     0.0133    1591248   8. include_once('/private/var/folders/fs/grc6ws5d37jfjbl27s73w8n40000gn/T/humbug.phpunit.bootstrap.php') /Users/anahkiasen/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:58
    >     0.0133    1593496   9. require_once('/Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/autoload.php') /private/var/folders/fs/grc6ws5d37jfjbl27s73w8n40000gn/T/humbug.phpunit.bootstrap.php:2
    >     0.0135    1609088  10. ComposerAutoloaderInit53a0ac4fb954920498b64b9da42c33b0::getLoader() /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/autoload.php:7
    >     0.0172    2049720  11. composerRequire53a0ac4fb954920498b64b9da42c33b0() /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/composer/autoload_real.php:49
    >     0.0173    2052392  12. require('/Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/nikic/php-parser/lib/bootstrap.php') /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/composer/autoload_real.php:58
    >     0.0177    2143496  13. require('/Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/nikic/php-parser/lib/PhpParser/Autoloader.php') /Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/nikic/php-parser/lib/bootstrap.php:3
    >
    >
```

**Comment by padraic** [comment]
Can you post the content of humbug.phpunit.bootstrap.php and there should also be a phpunit.humbug.xml file generated in same location? They should be retained after any run.

The error is because of the PhpParser boostrap being loaded which has an open ended require call, not require_once. Just trying to figure out what pre-loaded it in the first place to trigger that to error.

**Comment by Anahkiasen** [comment]
Hm no, all I have is my humbug.json and humbuglog.txt which just contains the error, do I need to pass a specific flag?

**Comment by padraic** [comment]
They're written out to the system temporary dir, e.g. /private/var/folders/fs/grc6ws5d37jfjbl27s73w8n40000gn/T/humbug.phpunit.bootstrap.php in the above exception details.

**Comment by Anahkiasen** [comment]
The bootstrap.php just contains this (which looks correct):

```php
<?php
require_once '/Users/anahkiasen/Sites/rocketeers/rocketeer/vendor/autoload.php';
```

No XML in sight though

**Comment by padraic** [comment]
A few other thoughts, are you using PHP 5.4 and, if so, do you happen to have apc.enable_cli set to 1? That can cause some unusual class clashes at times. The Composer guys check for it during installation.

The XML file must be getting deleted, not sure how long your testing takes - but you might be able to open and copy the contents mid-run when it's still in use. Mainly, I just want to see if it's pointing to the correct bootstrap file - from the above your own phpunit.xml would have rocketeer/vendor/autoload.php?

It's clearly the custom bootstrap for PhpParser which is non-Composer and enforced in their own composer.json so I'll have a go at reproducing tomorrow.

**Comment by Anahkiasen** [comment]
My own PHPUnit file points to [vendor/autoload.php](https://github.com/rocketeers/rocketeer/blob/develop/phpunit.xml) indeed, I don't even have the `apc.enable_cli` option, tested with a few versions and all seem to reproduce the issue.

**Comment by padraic** [comment]
Getting this after cloning and composer install (on develop branch - vendor/bin/phpunit) of rocketeer.

```
.............................array(13) {
  [1] =>
  string(3) "bin"
  [2] =>
  string(5) "build"
  [3] =>
  string(12) "CHANGELOG.md"
  [4] =>
  string(13) "composer.json"
  [5] =>
  string(13) "composer.lock"
  [6] =>
  string(15) "CONTRIBUTING.md"
  [7] =>
  string(11) "humbug.json"
  [8] =>
  string(7) "LICENSE"
  [9] =>
  string(11) "phpunit.xml"
  [10] =>
  string(9) "README.md"
  [11] =>
  string(3) "src"
  [12] =>
  string(5) "tests"
  [13] =>
  string(6) "vendor"
}
```
Something seems to be outputting the array (top level contents of base directory?) and then phpunit quits. Same happens with --tap option. Travis seems clean however so looks a bit odd. Test run ends in or just after Strategies/AbstractStrategyTest

Humbug continues its run however with the test suite recorded to that point:

```
padraic@padraic:~/projects/play/rocketeer$ ../../humbug/bin/humbug

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------] 3 secs

Humbug has completed the initial test run successfully.

Humbug is analysing source files...

Mutation Testing is commencing on 132 files...
(.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out)

SSS.SSSSSSSSSSSSSS.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |   60 ( 15/132)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  120 ( 21/132)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  180 ( 30/132)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  240 ( 61/132)
SS..E...S..EES....SSSSSSSSSSSSSSS...SS...SSSSSSSSSSSSSSSSSSS |  300 ( 99/132)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S..SSSSSSSSS.SSSS....SSSSSSSS |  360 (112/132)
SSSSSSSSSSSSSS.SS.SSSSS.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  420 (118/132)
SSSS.E......E......ESSSSSSSSSSSSSSSSSS....SSSSSSSSSSSSSSSSSS |  480 (124/132)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....SS....S....SS |  540 (130/132)
SSSS

544 mutations were generated:
      63 mutants were killed
     475 mutants were not covered by tests
       0 covered mutants were not detected
       6 fatal errors were encountered
       0 time outs were encountered

Out of 69 test covered mutations, 100% were detected.
Out of 544 total mutations, 13% were detected.
Out of 544 total mutations, 13% were covered by tests.

Remember that some mutants will inevitably be harmless (i.e. false positives).

Humbug results are being logged as JSON to: build/humbuglog.json
Humbug results are being logged as TEXT to: build/humbuglog.txt
```
Are you testing rocketeer itself, or something with it as a dependency?

**Comment by padraic** [comment]
@Anahkiasen Also, have you tried the current Humbug master? Some of the recent changes may had side effects to fix your issue - just want to confirm that is/is not the case here.

**Comment by Anahkiasen** [comment]
Sorry, pull develop and try again, one tests asserts that it can properly list files and it's getting bugged by the humbuglog.txt file that it's not expecting to find there. Made it check dynamically. Currently using dev-master, 849b767 to be more precise, bug still occurs as far as I can tell

**Comment by Anahkiasen** [comment]
Tried on a fresh copy of my repo and getting the same error so if it works on your end it must be a difference in our setup but I don't see what.

**Comment by Anahkiasen** [comment]
When you run PHPUnit from Humbug, does it include the package's vendor folder? If then couldn't it be just that I have a dependency in my global Composer dependencies that also requires php-parser and the two clash?

**Comment by padraic** [comment]
@Anahkiasen Humbug operates by taking the original phpunit.xml file (which will point at tests), and just adds logging and/or listener extensions. It doesn't influence where files are located, but it will filter them for speed or if unnecessary (e.g. we only run tests that actually cover a mutated line).

**Comment by Anahkiasen** [comment]
Yes but you're running the PHPUnit command in the current environment, not spawning a separate context, so the classes from my global dependencies will conflict with the package's when PHPUnit requires them to run the tests, isn't that it? See my edit above

**Comment by bobthecow** [comment]
@Anahkiasen Did you have psysh installed as a phar, or using the global Composer require? The latter causes all sorts of trouble, and I think we're going to stop suggesting people do it :-/

See https://github.com/bobthecow/psysh/issues/170

**Comment by Anahkiasen** [comment]
Latter yeah

**Comment by bobthecow** [comment]
Gotcha. Well, sorry. We're figuring out a way for this to work better :(

**Comment by padraic** [comment]
Closing as an old issue with known problem (dependency clash). If anyone drops by to read this, we have an issue opening separately to discuss and resolve (whether through isolation, better installation recommendation or other).

**Comment by bobthecow** [comment]
Sorry, this was fixed by bobthecow/psysh#172 which was shipped in [PsySH v0.5.1](https://github.com/bobthecow/psysh/releases/tag/v0.5.1) in March 2015. I didn't realize there was still an issue open about it :)

**Comment by padraic** [comment]
@bobthecow No worries. I've been...away...for a while ;).

**Comment by bobthecow** [comment]
@padraic welcome back then :)
